-- Add unlock override columns to school_assessments
ALTER TABLE school_assessments
ADD COLUMN IF NOT EXISTS unlocked_form_1 BOOLEAN DEFAULT FALSE NOT NULL,
ADD COLUMN IF NOT EXISTS unlocked_form_2 BOOLEAN DEFAULT FALSE NOT NULL,
ADD COLUMN IF NOT EXISTS unlocked_form_3 BOOLEAN DEFAULT FALSE NOT NULL,
ADD COLUMN IF NOT EXISTS unlocked_form_4 BOOLEAN DEFAULT FALSE NOT NULL;
